### ISSUE TITLE
Compatibility with django-grappelli

### ISSUE THREAD

**Issue by domenkozar** [jphalip/django-treemenus#10] opened 2011-08-18 10:11 UTC
In admin, arrow-down and arrow-up images do not appear.

$ grep -R "arrow-down" eggs/django_grappelli-2.3.3-py2.7.egg/
eggs/django_grappelli-2.3.3-py2.7.egg/EGG-INFO/SOURCES.txt:grappelli/static/grappelli/img/icons/icon-tools-arrow-down-handler-hover.png
eggs/django_grappelli-2.3.3-py2.7.egg/EGG-INFO/SOURCES.txt:grappelli/static/grappelli/img/icons/icon-tools-arrow-down-handler.png
eggs/django_grappelli-2.3.3-py2.7.egg/grappelli/static/grappelli/css/tools.css:.tools a.arrow-down-handler:link, .tools a.arrow-down-handler:visited {
eggs/django_grappelli-2.3.3-py2.7.egg/grappelli/static/grappelli/css/tools.css:    background-image: url('../img/icons/icon-tools-arrow-down-handler.png');
eggs/django_grappelli-2.3.3-py2.7.egg/grappelli/static/grappelli/css/tools.css:.tools a.arrow-down-handler:hover, .tools a.arrow-down-handler:active {
eggs/django_grappelli-2.3.3-py2.7.egg/grappelli/static/grappelli/css/tools.css:    background-image: url('../img/icons/icon-tools-arrow-down-handler-hover.png');

$ grep -R "arrow-down" eggs/django_treemenus-0.8.7_pre-py2.7.egg/
eggs/django_treemenus-0.8.7_pre-py2.7.egg/treemenus/templates/admin/treemenus/menu/change_form.html:                                            <td width="20" align="center"><a href="items/{{ menu_item.pk }}/move_down/"><img src="{% admin_media_prefix %}img/admin/arrow-down.gif" border="0" alt="{% trans 'Down' %}"/></b></td>

**Comment by jphalip** [comment] 2011-10-18 03:48
Under which version of Django is this failing?

**Comment by domenkozar** [comment] 2011-10-18 06:16
1.3

**Comment by jphalip** [comment] 2011-10-18 06:35
I've just tested with Django 1.3.1 and it's working fine.

Those two icons are shipping with Django itself. If they do not appear then it means that they are not properly served by your media server. This is likely not a bug in treemenus, so I'm closing this ticket. Please feel free to reopen if you can provide a test case or clearer instructions to reproduce this problem. Thanks!

**Closed as completed by jphalip** 2011-10-18 06:35 UTC

**Comment by domenkozar** [comment] 2011-10-18 07:13
I have reported this bug to django-grappeli, since it needs to be fixed there: https://github.com/sehmaschine/django-grappelli/issues/47
